import { test, expect } from '@playwright/test';

// Use the admin auth state generated by auth.setup.ts
test.use({ storageState: 'playwright/.auth/admin.json' });

test.describe('Admin Dashboard and CRUD', () => {

  test('admin dashboard loads correctly', async ({ page }) => {
    await page.goto('/admin', { waitUntil: 'domcontentloaded', timeout: 60000 });

    // Check that we didn't get redirected to login
    await expect(page).toHaveURL(/\/admin$/, { timeout: 15000 });

    // Check for dashboard elements
    await expect(page.getByRole('heading', { name: /dashboard/i }).first()).toBeVisible({ timeout: 15000 });
  });

  test('admin manga page loads', async ({ page }) => {
    await page.goto('/admin/manga', { waitUntil: 'domcontentloaded', timeout: 60000 });
    await expect(page).toHaveURL(/\/admin\/manga/, { timeout: 15000 });
    await expect(page.getByRole('heading').filter({ hasText: /manga/i }).first()).toBeVisible({ timeout: 15000 });
  });

  test('admin chapters page loads', async ({ page }) => {
    await page.goto('/admin/chapters', { waitUntil: 'domcontentloaded', timeout: 60000 });
    await expect(page).toHaveURL(/\/admin\/chapters/, { timeout: 15000 });
    await expect(page.getByRole('heading').filter({ hasText: /chapters/i }).first()).toBeVisible({ timeout: 20000 });
  });

  test('admin users page loads', async ({ page }) => {
    await page.goto('/admin/users', { waitUntil: 'domcontentloaded', timeout: 60000 });
    await expect(page).toHaveURL(/\/admin\/users/, { timeout: 15000 });
  });

  test('admin ads page loads', async ({ page }) => {
    await page.goto('/admin/ads', { waitUntil: 'domcontentloaded', timeout: 60000 });
    await expect(page).toHaveURL(/\/admin\/ads/, { timeout: 15000 });
  });

  test('admin audit-logs page loads', async ({ page }) => {
    await page.goto('/admin/audit-logs', { waitUntil: 'domcontentloaded', timeout: 60000 });
    await expect(page).toHaveURL(/\/admin\/audit-logs/, { timeout: 15000 });
  });

  test('admin settings page loads', async ({ page }) => {
    await page.goto('/admin/settings', { waitUntil: 'domcontentloaded', timeout: 60000 });
    await expect(page).toHaveURL(/\/admin\/settings/, { timeout: 15000 });
  });

  test('admin login page shows form (unauthenticated check)', async ({ browser, baseURL }) => {
    // Use a fresh context without the admin cookie to test the login page
    const ctx = await browser.newContext({ baseURL });
    const page = await ctx.newPage();
    await page.goto('/admin/login', { waitUntil: 'domcontentloaded', timeout: 60000 });
    // There are 2 forms on the page (navbar search + login form)
    // The login form is the last one and contains the email input
    await expect(page.locator('input[type="email"]')).toBeVisible({ timeout: 15000 });
    await expect(page.locator('input[type="password"]')).toBeVisible({ timeout: 15000 });
    await ctx.close();
  });

  test('admin API: manga list returns data', async ({ request }) => {
    const response = await request.get('/api/admin/manga');
    expect(response.ok()).toBeTruthy();
    const json = await response.json();
    expect(json.data).toBeDefined();
  });

  test('admin API: full CRUD lifecycle — manga → chapter → ad → cleanup', async ({ request }) => {
    // --- Create manga ---
    const createManga = await request.post('/api/admin/manga', {
      data: {
        title: 'Playwright E2E Test Manga',
        synopsis: 'This is an automated E2E test entry created by Playwright.',
        coverImage: 'https://res.cloudinary.com/dtdhpuqs/image/upload/v1/cld-sample',
        status: 'ONGOING',
        language: 'Japanese',
        isDraft: false,
        isFeatured: false,
        isTrending: false,
      },
    });
    expect(createManga.status()).toBe(201);
    const mangaJson = await createManga.json();
    const mangaId = mangaJson.data.id;
    const mangaSlug = mangaJson.data.slug;
    expect(mangaId).toBeTruthy();

    // --- Public API should now see this manga ---
    const publicManga = await request.get(`/api/manga/${mangaSlug}`);
    expect(publicManga.ok()).toBeTruthy();

    // --- Create chapter 1 ---
    const createChapter = await request.post('/api/admin/chapters', {
      data: {
        mangaId,
        chapterNumber: 1,
        title: 'Chapter 1',
        isPublished: true,
        pages: [
          { pageNumber: 1, imageUrl: 'https://res.cloudinary.com/dtdhpuqs/image/upload/v1/cld-sample' },
          { pageNumber: 2, imageUrl: 'https://res.cloudinary.com/dtdhpuqs/image/upload/v1/cld-sample-2' },
        ],
      },
    });
    expect(createChapter.status()).toBe(201);
    const chapterJson = await createChapter.json();
    const chapterId = chapterJson.data.id;

    // --- Create chapter 1.5 ---
    const createChapter15 = await request.post('/api/admin/chapters', {
      data: {
        mangaId,
        chapterNumber: 1.5,
        title: 'Chapter 1.5',
        isPublished: true,
        pages: [
          { pageNumber: 1, imageUrl: 'https://res.cloudinary.com/dtdhpuqs/image/upload/v1/cld-sample' },
        ],
      },
    });
    expect(createChapter15.status()).toBe(201);
    const chapter15Id = (await createChapter15.json()).data.id;

    // --- Edit manga ---
    const editManga = await request.patch(`/api/admin/manga/${mangaId}`, {
      data: { isFeatured: true, isTrending: true },
    });
    expect(editManga.ok()).toBeTruthy();

    // --- Create ad ---
    const createAd = await request.post('/api/admin/ads', {
      data: {
        name: 'Playwright Test Ad',
        type: 'GOOGLE_ADSENSE',
        position: 'HOME_HERO',
        content: '<div>Test Ad</div>',
        isActive: true,
      },
    });
    expect(createAd.status()).toBe(201);
    const adId = (await createAd.json()).data.id;

    // --- Delete chapter 1.5 ---
    const deleteChapter15 = await request.delete(`/api/admin/chapters/${chapter15Id}`);
    expect(deleteChapter15.ok()).toBeTruthy();

    // --- Edit chapter 1 ---
    const editChapter = await request.patch(`/api/admin/chapters/${chapterId}`, {
      data: { title: 'Chapter 1 (Edited)' },
    });
    expect(editChapter.ok()).toBeTruthy();

    // --- Delete ad ---
    const deleteAd = await request.delete(`/api/admin/ads/${adId}`);
    expect(deleteAd.ok()).toBeTruthy();

    // --- Delete manga (cascades chapters) ---
    const deleteManga = await request.delete(`/api/admin/manga/${mangaId}`);
    expect(deleteManga.ok()).toBeTruthy();

    // --- Verify deletion ---
    const deletedManga = await request.get(`/api/manga/${mangaSlug}`);
    expect(deletedManga.status()).toBe(404);
  });

});
